@echo off
setlocal

REM ====== CONFIGURE THESE VALUES ======
set SERVICE_NAME=ZillWrapper
set JAVA_EXE=C:\Program Files\Java\jdk-21\bin\java.exe
set APP_DIR=C:\apps\ZillWrapper
set APP_JAR=C:\apps\ZillWrapper\target\ZillWrapper-0.0.1-SNAPSHOT.jar

REM DB / APP secrets
set DB_URL=<PUT_DB_URL_HERE>
set DB_USER=<PUT_DB_USER_HERE>
set DB_PASS=<PUT_DB_PASS_HERE>
set APP_MASTER_KEY=<PUT_APP_MASTER_KEY_BASE64_HERE>

REM Mail secrets/config
set SPRING_MAIL_HOST=<PUT_SMTP_HOST_HERE>
set SPRING_MAIL_PORT=<PUT_SMTP_PORT_HERE>
set SPRING_MAIL_PROTOCOL=<PUT_SMTP_PROTOCOL_HERE>
set SPRING_MAIL_USERNAME=<PUT_SMTP_USERNAME_HERE>
set SPRING_MAIL_PASSWORD=<PUT_SMTP_PASSWORD_HERE>

REM Optional app env
set WHITE_ADMIN_BASE_URL=<PUT_WHITE_ADMIN_BASE_URL_HERE>
set WHITE_LOGIN=<PUT_WHITE_LOGIN_HERE>
set WHITE_PASSWORD=<PUT_WHITE_PASSWORD_HERE>
set ZILL_TOKEN=<PUT_TELEGRAM_BOT_TOKEN_HERE>
set DINO_BASE_URL=<PUT_DINO_BASE_URL_HERE>
set DINO_LOGIN=<PUT_DINO_LOGIN_HERE>
set DINO_PASSWORD=<PUT_DINO_PASSWORD_HERE>
set DINO_HARDWARE=<PUT_DINO_HARDWARE_HERE>

REM ====== INSTALL / UPDATE SERVICE ======
nssm install %SERVICE_NAME% "%JAVA_EXE%" "-jar %APP_JAR%"
nssm set %SERVICE_NAME% AppDirectory "%APP_DIR%"

nssm set %SERVICE_NAME% AppEnvironmentExtra ^
"DB_URL=%DB_URL%" ^
"DB_USER=%DB_USER%" ^
"DB_PASS=%DB_PASS%" ^
"APP_MASTER_KEY=%APP_MASTER_KEY%" ^
"SPRING_MAIL_HOST=%SPRING_MAIL_HOST%" ^
"SPRING_MAIL_PORT=%SPRING_MAIL_PORT%" ^
"SPRING_MAIL_PROTOCOL=%SPRING_MAIL_PROTOCOL%" ^
"SPRING_MAIL_USERNAME=%SPRING_MAIL_USERNAME%" ^
"SPRING_MAIL_PASSWORD=%SPRING_MAIL_PASSWORD%" ^
"WHITE_ADMIN_BASE_URL=%WHITE_ADMIN_BASE_URL%" ^
"WHITE_LOGIN=%WHITE_LOGIN%" ^
"WHITE_PASSWORD=%WHITE_PASSWORD%" ^
"ZILL_TOKEN=%ZILL_TOKEN%" ^
"DINO_BASE_URL=%DINO_BASE_URL%" ^
"DINO_LOGIN=%DINO_LOGIN%" ^
"DINO_PASSWORD=%DINO_PASSWORD%" ^
"DINO_HARDWARE=%DINO_HARDWARE%"

echo.
echo Service "%SERVICE_NAME%" configured.
echo Use:
echo   nssm start %SERVICE_NAME%
echo   nssm restart %SERVICE_NAME%

endlocal
