package com.zillya.timonfech.zillwrapper.core.entities;


public enum OperationType {
    ENTITY_SYNC,
    ENTITY_ENRICHMENT,
    LICENSE_FULFILLMENT,
    ORDER_CREATION,
    ORDER_UPDATE,
    LICENSE_GENERATION,
    LEGACY_SYNC,
    ARTIFACT_GENERATION,
    LICENSE_SUBSCRIPTION,
    SUSPENSION,
    DETACH_ACTIVATIONS,
    NOTIFY,
    RESEND_NOTIFICATION,
    EXTEND_ORDER,
    CONFIRMATION,
    LICENSE_SEARCH,
    MODIFY_STATUS,
    MODIFY_PERIOD,
    MODIFY_DEVICES,
    NONE
}
